server:
  port: 10000
spring:
  application:
    name: jeespring-gateway
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
        metadata:
          management:
            context-path: /actuator
          user.name: nacos
          user.password: nacos
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':                # 匹配所有请求
            allowedOrigins: "*"   #跨域处理,允许所有的域
            allowedMethods:       # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
# 暴露端点
management:
  endpoints:
    gateway:
      enable: true
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always